dns/amass: Really unbreak on aarch64
http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p520537_s355573/logs/errors/amass-3.4.2_1.log

# golang.org/x/net/ipv4
vendor/golang.org/x/net/ipv4/sys_asmreq.go:47:31: undefined: ipMreq
vendor/golang.org/x/net/ipv4/sys_freebsd.go:20:18: undefined: sysIP_RECVTTL
vendor/golang.org/x/net/ipv4/sys_freebsd.go:21:18: undefined: sysIP_RECVDSTADDR
vendor/golang.org/x/net/ipv4/sys_freebsd.go:22:18: undefined: sysIP_RECVIF
vendor/golang.org/x/net/ipv4/sys_freebsd.go:26:79: undefined: sysIP_TOS
vendor/golang.org/x/net/ipv4/sys_freebsd.go:27:79: undefined: sysIP_TTL
vendor/golang.org/x/net/ipv4/sys_freebsd.go:28:79: undefined: sysIP_MULTICAST_TTL
vendor/golang.org/x/net/ipv4/sys_freebsd.go:29:79: undefined: sysIP_MULTICAST_IF
vendor/golang.org/x/net/ipv4/sys_freebsd.go:60:11: undefined: groupReq
vendor/golang.org/x/net/ipv4/sys_freebsd.go:67:12: undefined: groupSourceReq

- golang.org/x/net also needs to be updated to at least 83d349e8ac1a

Approved by:	yuri (maintainer)